name = "kayak-polo-signup-email-handler"
account_id = "7b24a491f5dc20008fd759bb3a5b0636"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[[services]]
binding = "MAIN_APP"
service = "kayakpolosignups"
